const ROLES = {
    SUPERVISOR: 'supervisor',
    TECHNICAL: 'technical',
    USER: 'user'
}

const USER_RULES = {
    CREATE_USER: [ROLES.SUPERVISOR, ROLES.TECHNICAL],
    UPDATE_USER: [ROLES.SUPERVISOR, ROLES.TECHNICAL],
    DELETE_USER: [ROLES.SUPERVISOR],
    CHANGE_ROLE: [ROLES.SUPERVISOR],
    VIEW_ALL_USERS: [ROLES.SUPERVISOR, ROLES.TECHNICAL]
}

const TICKET_RULES = {
    CREATE_TICKET: [ROLES.USER, ROLES.SUPERVISOR, ROLES.TECHNICAL],
    UPDATE_TICKET: [ROLES.USER, ROLES.SUPERVISOR, ROLES.TECHNICAL],
    DELETE_TICKET: [ROLES.SUPERVISOR, ROLES.TECHNICAL],
    VIEW_ALL_TICKETS: [ROLES.USER, ROLES.SUPERVISOR, ROLES.TECHNICAL]
}

module.exports = { ROLES, USER_RULES }